Feature/setup database
indigotech/onboard-murilo-vidal pull request #8
Opened 2022-04-08 14:02 UTC by murilovidal

# Description

Added containerized database for local and test.

2022-04-08 14:12 UTC, alanraso approved these changes

2022-04-08 17:51 UTC, andrewmsilva requested changes
Tem várias alterações repetidas, então acho que valeria a pena fazer um rebase pra ajustar isso e o CR ser feito só no que realmente foi mexido.

2022-04-08 18:01 UTC, andrewmsilva approved these changes

2022-04-11 12:53 UTC, suyinyu approved these changes

2022-04-11 12:53 UTC, suyinyu commented on docker-compose.yml
> +    - .env.test
Nit: poderia acertar a indentação aqui

2022-04-11 16:31 UTC, merged